# config.yaml

default:
  proxy:
    scheme:                 http
    host:                   0.0.0.0
    port:                   8888
  mongodb:
    url:                    mongodb://localhost/rustafarian
  logger:
    level:                  debug
    path:                   service.log
    apiAccessLogPath:       api-access.log
    statsLevel:             info
    statsPath:              stats.log
    statsLogSecs:           60
